### ISSUE TITLE
Add to LuaRocks.org

### ISSUE THREAD

**Issue by leafo** [hsluv/hsluv-lua#1]
LuaRocks is the primary package manage for Lua: https://luarocks.org/

In order to add to the site you'll need to create a rockspec, then upload it.

https://github.com/keplerproject/luarocks/wiki/Creating-a-rock

Once added anyone can install this library by running `luarocks install husl`

**Comment by boronine** [comment]
Fixed: https://luarocks.org/modules/husl-colors/husl

Thank you for your interest!

**Comment by leafo** [comment]
Thanks!
